spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: none
cors:
  origins: https://api-rfilmes-production.up.railway.app,http://127.0.0.1:5500
security:
  key: ${SECRET_KEY}